export default [
	{ label: "Fade up", value: "fade-up" },
	{ label: "Fade down", value: "fade-down" },
	{ label: "Fade right", value: "fade-right" },
	{ label: "Fade left", value: "fade-left" },
	{ label: "Fade up right", value: "fade-up-right" },
	{ label: "Fade up left", value: "fade-up-left" },
	{ label: "Fade down right", value: "fade-down-right" },
	{ label: "Fade down left", value: "fade-down-left" },
	{ label: "Flip left", value: "flip-left" },
	{ label: "Flip right", value: "flip-right" },
	{ label: "Flip up", value: "flip-up" },
	{ label: "Zoom in", value: "zoom-in" },
	{ label: "Zoom in up", value: "zoom-in-up" },
	{ label: "Zoom in down", value: "zoom-in-down" },
	{ label: "Zoom in left", value: "zoom-in-left" },
	{ label: "Zoom in right", value: "zoom-in-right" },
	{ label: "Zoom out", value: "zoom-out" },
	{ label: "Zoom out up", value: "zoom-out-up" },
	{ label: "Zoom out down", value: "zoom-out-down" },
	{ label: "Zoom out right", value: "zoom-out-right" },
	{ label: "Zoom out left", value: "zoom-out-left" },
];
